
simulator:
  walking: False
  num_agents: 20
  num_targets: 1
  num_ground_targets: 1
  extract_submesh_target: True
  moving_targets: False
  num_episodes: 1
  num_frames: 1000
  target_creation_time: 500 # min is 1, which creates the target at the beginning of the episode.
  show_box: True
  # run_main_folder: "collab_env/sim/runs"
  run_main_folder: "sim-output"
  run_sub_folder_prefix: "boids_sim_run"

logging:
  logfile_prefix: 'logfile'
  log_level: 'DEBUG'
  logging: True
  log_functions: []

visuals:
  store_video: True
  show_visualizer: True
  width: 1920
  height: 1280
  video_codec: '*mpv4'
  video_fps: 30
  video_file_extension: 'mp4'
  agent_shape: 'sphere'
  agent_color: [1, 0, 0]
  agent_scale: 5.0
  target_scale: 20.0

environment:
  max_dist_from_center: 3
  box_size: 500
  scene_scale: 300.0
  scene_position: [250, 20, 250]
  target_speed: 0.0

agent:
  min_ground_separation: 5.0
  min_separation: 20.0
  neighborhood_dist: 80.0
  separation_weight: 15.0
  alignment_weight: 1.0
  cohesion_weight: 0.5
  ground_weight: 0.0
  target_weight: [1.0]
  max_speed: 1.0
  min_speed: 0.1
  max_force: 0.1
  mean_init_velocity: 0.0
  variance_init_velocity: 0.5
  init_range_low: 0.2
  init_range_high: 0.7

meshes:
    # mesh_scene: ''
    mesh_scene: 'meshes/Open3dTSDFfusion_mesh.ply'
    # mesh_scene: 'meshes/query-tree.ply'
    scene_angle: [-90.0, 0.0, 0.0]
    # scene_angle: [0.0, 0.0, 0.0]
    # mesh_scene: 'meshes/example_mesh.ply'
    # scene_angle: [-10.0, 0.0, -115.0]

files:
    output_folder_prefix: 'boids_sim_runs' # which of these am I using?
    trajectory_file:  'episode-0-completed-20250806-151621.parquet'
    trajectory_folder: 'sim-output/boids_sim_run-started-20250806-151619'