
simulator:
  walking: False
  num_agents: 40
  num_episodes: 1
  num_frames: 4000
  show_box: True
  run_main_folder: "collab_env/sim/runs"
  run_sub_folder_prefix: "boids_sim_run"
  logfile_prefix: 'logfile'
  log_level: 'DEBUG'
  logging: False
  log_functions: ['simpleBoidsAction']

visuals:
  store_video: False
  show_visualizer: True
  width: 1920
  height: 1280
  video_codec: '*mpv4'
  video_fps: 30
  video_file_extension: 'mp4'
  agent_shape: 'sphere'
  agent_color: [1, 0, 0]
  agent_scale: 5.0
  target_scale: 2.0

environment:
  max_dist_from_center: 3
  box_size: 500
  scene_scale: 300.0
  scene_position: [250, 20, 250]
  target_speed: 0.0
  target_creation_time: 2000

agent:
  min_ground_separation: 5.0
  min_separation: 20.0
  neighborhood_dist: 80.0
  separation_weight: 15.0
  alignment_weight: 1.0
  cohesion_weight: 0.1
  ground_weight: 0.0
  target_weight: 0.001
  max_speed: 0.5
  min_speed: 0.1
  max_force: 0.01
  mean_init_velocity: 0.0
  variance_init_velocity: 0.2

meshes:
    mesh_scene: ''
    # mesh_scene: 'meshes/Open3dTSDFfusion_mesh.ply'
    # mesh_scene: 'meshes/query-tree.ply'
    # scene_angle: [-90.0, 0.0, 0.0]
    # mesh_scene: 'meshes/example_mesh.ply'
    scene_angle: [-10.0, 0.0, -115.0]

files:
    output_folder_prefix: 'boids_sim_runs'